image: docker:19.03.0
    
services:
    - docker:19.03.0-dind

stages:
    - build-deploy
        
deploy:
    stage: build-deploy
    only:
        - master
    script:
        - docker build -t hawkmanlabs/tracker-mointoring-nginx-proxy:dev .

        - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
        
        - docker push hawkmanlabs/tracker-mointoring-nginx-proxy:stable